CREATE TABLE SITUACAO (
  Id_Situacao INTEGER PRIMARY KEY NOT NULL,
  Situacao VARCHAR(10)
);

CREATE TABLE SOCIO (
  Id_Socio INTEGER PRIMARY KEY NOT NULL,
  Nome VARCHAR(256),
  Cpf VARCHAR(11),
  Email VARCHAR(256),
  -- Relacionamentos
  FK_Situacao INTEGER,
  FOREIGN KEY (FK_Situacao) REFERENCES SITUACAO (Id_Situacao)
);

CREATE TABLE CARRO (
  Id_Carro INTEGER PRIMARY KEY NOT NULL,
  Modelo VARCHAR(128),
  Cor VARCHAR(64),
  Placa VARCHAR(10),
  -- Relacionamentos
  FK_Socio INTEGER,
  FK_Marca INTEGER,
  FOREIGN KEY (FK_Socio) REFERENCES SOCIO (Id_Socio),
  FOREIGN KEY (FK_Marca) REFERENCES MARCA (Id_Marca)
);



CREATE TABLE MARCA (
  Id_Marca INTEGER PRIMARY KEY NOT NULL,
  Marca VARCHAR(128)
);
